# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true
# command_timeout = 10000

# Change the default prompt format
format = """\
[╭╴](238)$os$username$hostname\
$all[╰─](238)$character"""

[os]
format = "[$symbol]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Windows = " "
Ubuntu = " "

[hostname]
ssh_only = false
format = 'on [$hostname](bold red) '
disabled = false

# Change the default prompt characters
[character]
success_symbol = "[](238)"
error_symbol = "[](238)"

# Shows the username
[username]
format = "[$user]($style) "
# style_user = "white bold"
# style_root = "black bold"
# format = 'user: [$user]($style) '
disabled = false  # disable in powershell
show_always = true

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

[git_status]
# format = '[\($all_status$ahead_behind\)]($style) '
format = ''
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[docker_context]
format = "via [ $context](bold blue) "

[python]
symbol = " "
python_binary = "python3"

[nodejs]
format = "via [ $version](bold green) "
disabled = true
